export const KEYS = {
  AUTH: {
    LOGIN: "admin-login",
    REGISTER: "admin-register",
    FORGOT_PASSWORD: "forgot-password",
    VERIFY_OTP: "otp-verify",
    RESET_PASSWORD: "reset-password",
    RESEND_OTP: "resend-otp",
    CHANGE_PASSWORD: "change-password",
    UPDATE_PROFILE: "update-profile",
    DELETE_ACCOUNT: "delete-account",
  },
  USER: {
    BASE: "user",
    ADD: "add-user",
    EDIT: "edit-user",
    DELETE: "delete-user",
  },
  COURSE: {
    BASE: "course",
    ADD: "add",
    edit: "update",
    DELETE: "delete",
    VERIFY: "verify",
    PURCHASE: "purchase",
    MY_COURSES: "my-courses",
  },
  CURRICULUM: {
    BASE: "course-curriculum",
    ADD: "add",
    edit: "edit",
    DELETE: "delete",
  },
  LESSON: {
    BASE: "course-lesson",
    ADD: "add",
    edit: "edit",
    DELETE: "delete",
  },
  EXAM: {
    BASE: "exam",
    ADD: "add",
    edit: "edit",
    DELETE: "delete",
    ATTEMPTS: "attempts",
    SUBMIT: "submit",
  },
  QUESTION: {
    BASE: "question",
    ADD: "add",
    edit: "edit",
    DELETE: "delete",
  },
  WORKSHOP: {
    BASE: "workshop",
    ADD: "add",
    edit: "edit",
    DELETE: "delete",
    PURCHASE: "purchase",
    MY_COURSES: "my-workshops",
  },
  WORKSHOP_CURRICULUM: {
    BASE: "workshop-curriculum",
    ADD: "add",
    edit: "edit",
    DELETE: "delete",
  },
  TESTIMONIAL: {
    BASE: "testimonial",
    ADD: "add",
    EDIT: "edit",
    DELETE: "delete",
  },
  FAQ: {
    BASE: "faq",
    ADD: "add",
    EDIT: "edit",
    DELETE: "delete",
  },
  BLOG: {
    BASE: "blog",
    ADD: "add",
    EDIT: "edit",
    DELETE: "delete",
  },
  HERO_BANNER: {
    BASE: "hero-banner",
    ADD: "add",
    EDIT: "edit",
    DELETE: "delete",
  },
  ABOUT_US: {
    BASE: "about-us",
  },
  DASHBOARD: {
    BASE: "dashboard",
    ANALYTICS: "dashboard-analytics",
    LOGIN_HISTORY: "dashboard-login-history",
  },
  CHAT: {
    BASE: "chat",
    ROOMS: "chat-rooms",
    MESSAGES: "chat-messages",
  },
  SETTING: {
    BASE: "settings",
    ADD_EDIT: "add-edit",
  },
  GET_IN_TOUCH: {
    BASE: "get-in-touch",
    DELETE: "delete-get-in-touch",
  },
  COUPON_CODE: {
    BASE: "coupon-code",
    DELETE: "delete-coupon-code",
  },
  CONTACT_US: {
    BASE: "contact-us",
  },
  LEGALITY: {
    BASE: "legality",
  },
  GALLERY: {
    BASE: "gallery",
    DELETE: "delete-gallery",
  },
  NEWSLETTER: {
    BASE: "newsletter",
    DELETE: "delete-newsletter",
  },
  NOTIFICATION: {
    BASE: "notification",
    GET: "get-notifications",
    READ: "read-notification",
    DELETE: "delete-notification",
  },
  TRUSTED_PARTNER: {
    BASE: "trusted-partner",
    DELETE: "delete-trusted-partner",
  },
  FRANCHISE_INQUIRY: {
    BASE: "franchise-inquiry",
    DELETE: "delete-franchise-inquiry",
  },
};
