export const URL_KEYS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/signup",
    FORGOT_PASSWORD: "/auth/forgot-password",
    VERIFY_OTP: "/auth/otp/verify",
    RESET_PASSWORD: "/auth/reset-password",
    RESEND_OTP: "/auth/resend-otp",
    CHANGE_PASSWORD: "/auth/change-password",
    UPDATE_PROFILE: "/auth/update-profile",
    DELETE_ACCOUNT: "/auth/delete-account",
  },
  USER: {
    UPDATE_PROFILE: "/user/profile",
    UPDATE: "/user/update",
    BASE: "/user",
    GET: "/user/all",
    ADD: "/user/add",
    UPADTE: "/user/update",
    DELETE: "/user/delete",
  },
  COURSE: {
    BASE: "/course",
    ADD: "/course/add",
    EDIT: "/course/update",
    DELETE: "/course/delete",
    GET: "/course/all",
    PURCHASE: "/course/purchase",
    MY_COURSES: "/course/my-courses",
    VERIFY: "/course/verify",
  },
  CURRICULUM: {
    ADD: "/course-curriculum/add",
    EDIT: "/course-curriculum/edit",
    DELETE: "/course-curriculum/delete", 
    GET: "/course-curriculum/all",
    BASE: "/course-curriculum",  
  },
  LESSON: {
    ADD: "/course-lesson/add",
    EDIT: "/course-lesson/edit",
    DELETE: "/course-lesson/delete",
    GET: "/course-lesson/all",
    BASE: "/course-lesson",
  },
  EXAM: {
    ADD: "/exam/add",
    EDIT: "/exam/edit",
    DELETE: "/exam/delete",
    GET: "/exam/all",
    BASE: "/exam",
  },
  QUESTION: {
    ADD: "/question/add",
    EDIT: "/question/edit",
    BASE: "/question/delete",
    GET: "/question/all",
  },
  WORKSHOP: {
    BASE: "/workshop",
    ADD: "/workshop/add",
    EDIT: "/workshop/edit",
    DELETE: "/workshop/delete",
    GET: "/workshop/all",
    PURCHASE: "/workshop/purchase",
    MY_WORKSHOPS: "/workshop/my-workshops",
  },
  WORKSHOP_CURRICULUM: {
    ADD: "/workshop-curriculum/add",
    EDIT: "/workshop-curriculum/edit",
    DELETE: "/workshop-curriculum/delete",
    GET: "/workshop-curriculum/all",
    BASE: "/workshop-curriculum",
  },
  TESTIMONIAL: {
    ADD: "/testimonial/add",
    EDIT: "/testimonial/edit",
    DELETE: "/testimonial/delete",
    GET: "/testimonial/all",
    BASE: "/testimonial",
  },
  FAQ: {
    ADD: "/faq/add",
    EDIT: "/faq/edit",
    DELETE: "/faq/delete",
    GET: "/faq/all",
    BASE: "/faq",
  },
  BLOG: {
    ADD: "/blog/add",
    EDIT: "/blog/edit",
    DELETE: "/blog/delete",
    GET: "/blog/all",
    BASE: "/blog",
  },
  HERO_BANNER: {
    ADD: "/hero-banner/add",
    EDIT: "/hero-banner/edit",
    DELETE: "/hero-banner/delete",
    GET: "/hero-banner/all",
    BASE: "/hero-banner",
  },
  ABOUT_US: {
    BASE: "/about-us",
    EDIT: "/about-us/add/edit",
  },
  DASHBOARD: {
    BASE: "/dashboard",
    GET: "/dashboard",
    ANALYTICS: "/dashboard/analytics",
  },
  CHAT: {
    SEND: "/chat/send",
    ROOMS: "/chat/rooms",
    MESSAGES: "/chat/messages",
    CREATE_ROOM: "/chat/room/create",
  },
  SETTING: {
    ALL: "/settings/all",
    ADD_EDIT: "/settings/add-edit",
  },
  GET_IN_TOUCH: {
    BASE: "/get-in-touch",
    ADD: "/get-in-touch/add",
    EDIT: "/get-in-touch/edit",
    DELETE: "/get-in-touch/delete",
    GET: "/get-in-touch/all",
  },
  COUPON_CODE: {
    BASE: "/coupon-code",
    ADD: "/coupon-code/add",
    EDIT: "/coupon-code/edit",
    DELETE: "/coupon-code/delete",
    GET: "/coupon-code/all",
  },
  CONTACT_US: {
    BASE: "/contact-us",
    GET: "/contact-us/all",
    ADD_EDIT: "/contact-us/add-edit",
  },
  LEGALITY: {
    BASE: "/legality",
    ADD: "/legality/add",
    EDIT: "/legality/add",
    GET: "/legality",
  },
  GALLERY: {
    BASE: "/gallery",
    ADD: "/gallery/add",
    EDIT: "/gallery/edit",
    DELETE: "/gallery/delete",
    GET: "/gallery/all",
  },
  NEWSLETTER: {
    BASE: "/newsletter",
    ADD: "/newsletter/add",
    DELETE: "/newsletter/delete",
    GET: "/newsletter/all",
    SEND: "/newsletter/send",
  },
  NOTIFICATION: {
    GET: "/notification/all",
    READ: "/notification/read",
    DELETE: "/notification/delete",
  },
  TRUSTED_PARTNER: {
    BASE: "/trusted-partner",
    ADD: "/trusted-partner/add",
    EDIT: "/trusted-partner/edit",
    DELETE: "/trusted-partner/delete",
    GET: "/trusted-partner/all",
  },
  FRANCHISE_INQUIRY: {
    BASE: "/franchise-inquiry",
    DELETE: "/franchise-inquiry/delete",
    EDIT: "/franchise-inquiry/edit",
    GET: "/franchise-inquiry/all",
  },
} as const;
