export const URL_KEYS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    FORGOT_PASSWORD: "/auth/forgot-password",
  },
  USER: {
    UPDATE_PROFILE: "/user/profile",
    UPDATE: "/user/update",
    BASE: "/user",
    GET: "/user/get",
  },
  DASHBOARD: {
    BASE: "/dashboard",
  },
  UPLOAD: {
    ADD: "/upload",
    DELETE: "/upload/delete",
    IMAGES: "/upload/images",
    PDFS: "/upload/pdfs",
  },
  HERO_SECTION: {
    BASE: "/hero-section",
    GET: "/hero-section/get",
    UPDATE: "/hero-section/update",
  },
  WORK_COUNT: {
    BASE: "/work-count",
    ALL: "/work-count/all",
    ADD: "/work-count/add",
    EDIT: "/work-count/edit",
    DELETE: "/work-count/delete",
  },
  BLOG: {
    BASE: "/blog",
    ALL: "/blog/all",
    ADD: "/blog/add",
    EDIT: "/blog/edit",
    DELETE: "/blog/delete",
  },
  SERVICE: {
    BASE: "/service",
    ALL: "/service/all",
    ADD: "/service/add",
    EDIT: "/service/edit",
    DELETE: "/service/delete",
  },
  BUSINESS_CATEGORY: {
    BASE: "/business-category",
    ALL: "/business-category/all",
    ADD: "/business-category/add",
    EDIT: "/business-category/edit",
    DELETE: "/business-category/delete",
  },
  PORTFOLIO: {
    BASE: "/portfolio",
    ALL: "/portfolio/all",
    ADD: "/portfolio/add",
    EDIT: "/portfolio/edit",
    DELETE: "/portfolio/delete",
  },
  OUR_SERVICE: {
    BASE: "/our-service",
    ALL: "/our-service/all",
    ADD: "/our-service/add",
    EDIT: "/our-service/edit",
    DELETE: "/our-service/delete",
  },
  CLIENT_LOGO: {
    BASE: "/client-logo",
    ALL: "/client-logo/all",
    ADD: "/client-logo/add",
    EDIT: "/client-logo/edit",
    DELETE: "/client-logo/delete",
  },
  WORK_EXPERIENCE: {
    BASE: "/work-experience",
    ALL: "/work-experience/all",
    ADD: "/work-experience/add",
    EDIT: "/work-experience/edit",
    DELETE: "/work-experience/delete",
  },
  SKILL: {
    BASE: "/skill",
    ALL: "/skill/all",
    ADD: "/skill/add",
    EDIT: "/skill/edit",
    DELETE: "/skill/delete",
  },
  AWARDS: {
    BASE: "/awards",
    ALL: "/awards/all",
    ADD: "/awards/add",
    EDIT: "/awards/edit",
    DELETE: "/awards/delete",
  },
  TESTIMONIAL: {
    BASE: "/testimonial",
    ALL: "/testimonial/all",
    ADD: "/testimonial/add",
    EDIT: "/testimonial/edit",
    DELETE: "/testimonial/delete",
  },
  TESTIMONIAL_DESCRIPTION: {
    BASE: "/testimonial-description",
    GET: "/testimonial-description/get",
    UPDATE: "/testimonial-description/update",
  },
  CONTACT_US: {
    BASE: "/contact-us",
    ALL: "/contact-us/all",
    ADD: "/contact-us/add",
    EDIT: "/contact-us/edit",
    DELETE: "/contact-us/delete",
  },
  MY_ACHIEVEMENT: {
    BASE: "/my-achievement",
    ALL: "/my-achievement/all",
    ADD: "/my-achievement/add",
    EDIT: "/my-achievement/edit",
    DELETE: "/my-achievement/delete",
  },
  PRIVACY_POLICY: {
    BASE: "/privacy-policy",
    GET: "/privacy-policy/get",
    UPDATE: "/privacy-policy/update",
  },
  TERMS_CONDITIONS: {
    BASE: "/terms-conditions",
    GET: "/terms-conditions/get",
    UPDATE: "/terms-conditions/update",
  },
  SETTING: {
    BASE: "/setting",
    GET: "/setting/get",
    UPDATE: "/setting/update",
  },
} as const;
